version: "3.9"
# ref: https://docs.docker.com/compose/compose-file
services:
  app:
    image: gotodo
    build:
      args:
        - target=dev
    environment:
      TODO_ENV: dev
      PORT: 8080
    volumes:
      - .:/app
    ports:
      - "18000:8080"